framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        buses:
            command.bus: ~

        transports:
#            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
#            'App\Common\AbstractCommand': async
